### ISSUE TITLE
为什么本地打开源码没有点位显示？

### ISSUE THREAD

**Issue by martjay** [xunfengawa/xunfengawa.github.io#1]
如题，我打开github.io那个网页可以显示点位

**Comment by xunfengawa** [comment]
因为我用的XMLHttpRequest去读的json文件，在本地会因为安全问题被拦截。
已经在学习其他读取json的方式啦~
但是本地想用暂时只能开个虚拟服务端或什么的（推荐用vscode的html相关插件）
Access to XMLHttpRequest at './locs/WorldsEdge.json' from origin 'null' has been blocked by CORS policy

**Comment by xunfengawa** [comment]
暂时通过访问云端json文件解决了这个问题，代价就是必须联网使用。
等以后有空再去学习解决前端跨域问题啦。
